"""seed data

Revision ID: e85801fcd680
Revises: f7f9b27c05a2
Create Date: 2025-12-31 11:57:05.066591

"""

from typing import Sequence, Union

from sqlalchemy_training.seed import delete_records, seed_fake_data

# revision identifiers, used by Alembic.
revision: str = "e85801fcd680"
down_revision: Union[str, Sequence[str], None] = "f7f9b27c05a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    seed_fake_data()
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    delete_records()
    # ### end Alembic commands ###
