"""change products and users

Revision ID: f7f9b27c05a2
Revises: fb4f978c2275
Create Date: 2025-12-31 07:23:28.475890

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7f9b27c05a2"
down_revision: Union[str, Sequence[str], None] = "fb4f978c2275"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("price", sa.DECIMAL(precision=16, scale=4), nullable=False),
    )
    op.alter_column(
        "products",
        "description",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.VARCHAR(length=3000),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "username",
        new_column_name="user_name",
    )
    op.alter_column(
        "users",
        "language_code",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "user_name",
        new_column_name="username",
    )
    op.alter_column(
        "users",
        "language_code",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "description",
        existing_type=sa.VARCHAR(length=3000),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.drop_column("products", "price")
    # ### end Alembic commands ###
